### ISSUE TITLE
Move_group takes a long time to start

### ISSUE THREAD

**Issue by hersh** [moveit/moveit_ros#380]
This is a follow-on to #378.

Move_group is taking around 30 seconds to start for me, using a PR2 model.

I did a little investigating, and almost all of that time is spent inside shapes::Mesh::mergeVertices().  This is a mesh-simplification function which reduces the vertex count of a detailed mesh by doing an N-squared search for vertices which are closer than a threshold (in my application looks like 0.1mm).

What would it take to process these stupid PR2 meshes down into something reasonable and then push them back into the pr2_description package?  I remember looking into this before for some reason, and they have things like phillips screw heads modeled in exacting detail.  There's no reason for that much detail on the models used for any kind of motion planning.

The other obvious thing to do is use something faster than N-squared for the mesh simplification, but I hesitate to put much time into that when we could just run it on our robot models once and it would be fixed.

**Comment by mikeferguson** [comment]
Hersh, are you compiling in debug mode? I found that for our robot, the meshes are very non-optimized right now (~44mb vs 5mb for the PR2), and that normal loading took ~20s, but in debug mode it could take several minutes -- making it very painful to debug some of the segfaults I fixed in pick and place back in September.

**Comment by hersh** [comment]
Yes, this is in debug mode.  I'm sure it would run faster in normal mode, but I believe the bug is still valid because of the need for debugging if nothing else.

What it really says to me is that somewhere in the process of creating a URDF there should be an optimization step, where meshes are simplified to a level of detail appropriate for path planning.

**Comment by mikeferguson** [comment]
Oh I definitely believe it is valid, it was more that I didn't remember PR2 taking 30s in non-debug mode, and so I wanted to see if we have a serious recent regression or whatnot.

The PR2 itself had some significant work done to optimize its meshes, but it was all manual. A tool that optimizes the meshes planning would be valuable for importing robots.

**Comment by hersh** [comment]
@mikeferguson Well I've now done the "decimation" of meshes that I needed for the PR2 and I have to say it was pretty easy.  Not automated with a script, but the actual geometric decimation work is all done nicely.  I just used "blender", the free 3D drawing program.  For each .stl file used for collision checking, I imported it into an empty scene, then used the decimate modifier ( http://wiki.blender.org/index.php/Doc:2.6/Manual/Modifiers/Generate/Decimate ) interactively to choose how much to change the mesh.  It responds pretty much immediately, so it is easy to try different decimation ratios and choose the smallest ratio that still preserves the geometry that you care about. Once you find a ratio you like you have to click "apply" for the changes to take affect. Then I just exported the mesh back to the same .stl file, deleted it from the scene, and imported the next one.  The 8 or 10 meshes I did probably took me about 2 hours.

Anyway, it sped up testing a lot because that part of move_group initialization now takes less than a second even in debug mode.  So I highly recommend doing it for the 44mb of meshes of your robot.
